export const categories = {
  beauty: { title: 'Beauty', color: '#FF6B6B' },
  fragrances: { title: 'Fragrances', color: '#4ECDC4' },
  furniture: { title: 'Furniture', color: '#45B7D1' },
  groceries: { title: 'Groceries', color: '#FFA07A' },
  'home-decoration': { title: 'Home Decoration', color: '#98D8C8' },
  'kitchen-accessories': { title: 'Kitchen Accessories', color: '#F7DC6F' },
  laptops: { title: 'Laptops', color: '#BB8FCE' },
  'mens-shirts': { title: "Men's Shirts", color: '#A8E6CF' },
  'mens-shoes': { title: "Men's Shoes", color: '#D7DBDD' },
  'mens-watches': { title: "Men's Watches", color: '#F1948A' },
  'mobile-accessories': { title: 'Mobile Accessories', color: '#85C1E9' },
  motorcycle: { title: 'Motorcycles', color: '#5D6D7E' },
  'skin-care': { title: 'Skin Care', color: '#E8DAEF' },
  smartphones: { title: 'Smartphones', color: '#F8C471' },
  'sports-accessories': { title: 'Sports Accessories', color: '#82E0AA' },
  sunglasses: { title: 'Sunglasses', color: '#F9E79F' },
  tablets: { title: 'Tablets', color: '#D2B4DE' },
  tops: { title: 'Tops', color: '#AED6F1' },
  vehicle: { title: 'Vehicles', color: '#ABEBC6' },
  'womens-bags': { title: "Women's Bags", color: '#F5B7B1' },
  'womens-dresses': { title: "Women's Dresses", color: '#D7BDE2' },
  'womens-jewellery': { title: "Women's Jewellery", color: '#FADBD8' },
  'womens-shoes': { title: "Women's Shoes", color: '#D5F5E3' },
  'womens-watches': { title: "Women's Watches", color: '#5DADE2' },
};
