export const categories = {
  beauty: { title: 'Belleza', color: '#FF6B6B' },
  fragrances: { title: 'Fragancias', color: '#4ECDC4' },
  furniture: { title: 'Muebles', color: '#45B7D1' },
  groceries: { title: 'Abastecimientos', color: '#FFA07A' },
  'home-decoration': { title: 'Decoración del hogar', color: '#98D8C8' },
  'kitchen-accessories': { title: 'Accesorios de cocina', color: '#F7DC6F' },
  laptops: { title: 'Portátiles', color: '#BB8FCE' },
  'mens-shirts': { title: 'Camisas de hombre', color: '#A8E6CF' },
  'mens-shoes': { title: 'Zapatos de hombre', color: '#D7DBDD' },
  'mens-watches': { title: 'Relojes de hombre', color: '#F1948A' },
  'mobile-accessories': { title: 'Accesorios móviles', color: '#85C1E9' },
  motorcycle: { title: 'Motocicletas', color: '#5D6D7E' },
  'skin-care': { title: 'Cuidado de la piel', color: '#E8DAEF' },
  smartphones: { title: 'Teléfonos inteligentes', color: '#F8C471' },
  'sports-accessories': { title: 'Accesorios deportivos', color: '#82E0AA' },
  sunglasses: { title: 'Gafas de sol', color: '#F9E79F' },
  tablets: { title: 'Tablets', color: '#D2B4DE' },
  tops: { title: 'Blusas', color: '#AED6F1' },
  vehicle: { title: 'Vehículos', color: '#ABEBC6' },
  'womens-bags': { title: 'Bolsos de mujer', color: '#F5B7B1' },
  'womens-dresses': { title: 'Vestidos de mujer', color: '#D7BDE2' },
  'womens-jewellery': { title: 'Joyería de mujer', color: '#FADBD8' },
  'womens-shoes': { title: 'Zapatos de mujer', color: '#D5F5E3' },
  'womens-watches': { title: 'Relojes de mujer', color: '#5DADE2' },
};
